version: "3.8"


services:

  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nba_db
    #volumes:
    #  - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
       - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"
    depends_on:
      - postgres